// <auto-generated />
namespace Katalog.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DropColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201505061737416_DropColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
