// <auto-generated />
namespace Katalog.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class migracja : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migracja));
        
        string IMigrationMetadata.Id
        {
            get { return "201505271529273_migracja"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
