// <auto-generated />
namespace Katalog.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddSitesWithOpinions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSitesWithOpinions));
        
        string IMigrationMetadata.Id
        {
            get { return "201810170814510_AddSitesWithOpinions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
